trigger:
  branches:
    include:
      - main
      - develop

pr:
  branches:
    include:
      - main
      - develop
  drafts: false

pool:
  vmImage: ubuntu-latest

steps:
- script: npm ci
  displayName: 'Install Dependencies'

- script: npm run lint:fix
  displayName: 'Linting'

- script: npm run build
  displayName: 'Build React webApp'

- script: npm test -- --ci --watchAll=false --passWithNoTests
  displayName: 'Running Unit Test'

- task: PublishBuildArtifacts@1
  displayName: 'Save Artifact'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  inputs:
    PathtoPublish: '$(Agent.BuildDirectory)/s/build'
    ArtifactName: 'drop'
    publishLocation: 'Container'
