trigger:
  branches:
    include:
      - master
      - develop

pr:
  branches:
    include:
      - master
      - develop
  drafts: false

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.17.x' 
  displayName: 'Install Node'

- script: npm ci
  displayName: 'Install dependencies'

- script: npm run build
  displayName: 'Build React webApp'

- task: PublishBuildArtifacts@1
  displayName: 'Save artifact'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  inputs:
    PathtoPublish: '$(Agent.BuildDirectory)/s/build'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  