# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.17.x' 
  #force32bit: false # Optional
  #checkLatest: false # Optional #version LTS o latest de node

 # installing dependencies (react, axios, etc)
- script: npm install

# building the webApp
- script: npm run build 

